services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: moodmate
      POSTGRES_PASSWORD: moodmate
      POSTGRES_DB: moodmate
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ai-api:
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - postgres
    env_file:
      - ./ai-api/.env

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend:/spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ai-api
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/build
    ports:
      - "3000:3000"

volumes:
  postgres-data:
  backend:
  frontend:
