
x-infisical-env: &infisical-env
  INFISICAL_TOKEN: ${INFISICAL_TOKEN}
  INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
  INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
  INFISICAL_HOST: ${INFISICAL_HOST}


services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: moodmate
      POSTGRES_PASSWORD: moodmate
      POSTGRES_DB: moodmate
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

  ai-api:
    build:
      context: ./ai-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      <<: *infisical-env

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ai-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
      <<: *infisical-env
    command: |
      gradle bootRun --args='--spring.profiles.active=dev' --continuous

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend-api
    ports:
      - "3000:3000"
    environment:
      <<: *infisical-env
