apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodmate-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: moodmate.rst0070.com
    http:
      paths:
        - path: /api/v1
          pathType: Prefix
          backend:
            service:
              name: backend-api
              port:
                number: 8080
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: ai-api
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000
