services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: moodmate
      POSTGRES_PASSWORD: moodmate
      POSTGRES_DB: moodmate
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build/libs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moodmate
      SPRING_DATASOURCE_USERNAME: moodmate

volumes:
  postgres-data:
      