services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 9878
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build/libs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev

volumes:
  postgres-data:
