apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ai-api
  name: ai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ai-api
    spec:
      containers:
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GEMINI_API_KEY
                  name: ai-api--env
          image: ai-api
          name: ai-api
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
