apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: moodmate-ai-api
  name: ai-api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service-name: moodmate-ai-api
status:
  loadBalancer: {}
