apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
  storageClassName: gp2
status: {}