apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-api
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: backend-api
          name: backend-api
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /spring
              name: backend
      restartPolicy: Always
      volumes:
        - name: backend
          persistentVolumeClaim:
            claimName: backend
status: {}
