apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: moodmate-backend-api
  name: backend-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service-name: moodmate-backend-api
status:
  loadBalancer: {}
