apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: harbor.rst0070.com/moodmate/frontend:latest
          name: frontend
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /build
              name: frontend
      restartPolicy: Always
      volumes:
        - name: frontend
          persistentVolumeClaim:
            claimName: frontend
status: {}
