apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: moodmate-frontend
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service-name: moodmate-frontend
status:
  loadBalancer: {}
