apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
status: {}
