apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: moodmate-postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service-name: moodmate-postgres
status:
  loadBalancer: {}
