apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-data
  name: postgres-data
spec:
  storageClassName: efs-postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: gp2
status: {}