server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  service:
    ai-api:
      chat-url: http://localhost:8000/v1/chat/completion

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/moodmate
    username: moodmate
    password: moodmate
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
    
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    path: /swagger-ui
    disableSwaggerDefaultUrl: false
    docExpansion: list
  paths-to-match:
  - /api/**
  show-actuator: true