spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/moodmate
    username: moodmate
    password: moodmate
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    operationsSorter: alpha
    tagsSorter: alpha
    path: ${SWAGGER_PATH:/swagger-ui}
  show-actuator: true