server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "32401732479-rsoptcn5f1liia0r098japg3ofgp5t6k.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: test
    password: 9878
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    path: /swagger-ui/index.html
    disableSwaggerDefaultUrl: false
    docExpansion: list
  paths-to-match:
  - /api/**
  show-actuator: true