# postgresql.yaml

# postgreSQL Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pgsql

---

# postgreSQL Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ''

---

# postgreSQL ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: pgsql-config
  labels:
    app: pgsql-config
data:
  POSTGRES_USER: moodmate
  POSTGRES_PASSWORD: moodmate

#---
#
## postgreSQL Pod
#
#apiVersion: v1
#kind: Pod
#metadata:
#  name: pgsql-pod
#  labels:
#    name: pgsql-pod
#spec:
#  containers:
#  - name: postgresql
#    image: postgres:17.4
#    env:
#    - name: POSTGRES_USER
#      value: "moodmate"
#    - name: POSTGRES_PASSWORD
#      value: "moodmate"
#    resources:
#      limits:
#        memory: "1024Mi"
#        cpu: "500m"
#    ports:
#      - containerPort: 5432

---

# postgreSQL Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-server-deployment
  labels:
    app: pgsql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql-server
  template:
    metadata:
      labels:
        app: pgsql-server
    spec:
      containers:
      - name: postgresql
        image: postgres:17.4
        env:
        - name: POSTGRES_USER
          value: "moodmate"
        - name: POSTGRES_PASSWORD
          value: "moodmate"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

---

# postgreSQL Service

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432

