# .github/workflows/docker-build-push.yml

name: Docker Build and Push to Harbor

# 1. When the workflow should run
on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
      - feat/gh-action
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'ai-api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'ai-api/**'
  # workflow_dispatch: 


# 2. Define one or more jobs
jobs:
  build_and_push: 
    runs-on: ubuntu-latest

    # 3. Steps within the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to your private Harbor registry
      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY_URL }} 
          username: ${{ secrets.HARBOR_USERNAME }} 
          password: ${{ secrets.HARBOR_PASSWORD }} 

      # Step 4: Build the Docker image
      - name: Build Docker Image
        # The 'run' keyword executes shell commands
        run: |
          echo "Building Docker image..."
          docker build -t ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/backend:latest ./backend
          docker build -t ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/frontend:latest ./frontend
          docker build -t ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/ai-api:latest ./ai-api

      # Step 5: Push the Docker image to Harbor
      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to Harbor..."
          docker push ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/backend:latest
          docker push ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/frontend:latest
          docker push ${{ secrets.HARBOR_REGISTRY_URL }}/moodmate/ai-api:latest